@startuml

header Демо проект
title Схема БД

hide circle
skinparam linetype ortho


entity customers {
  * **id**  :  int
  __
  **email**  :  varchar
}

entity products {
  * **sku**  :  varchar
  __
  * **title**  :  varchar
  --
  * **description**  :  varchar
  --
  * **price**  :  float
}

entity carts {
  * **id**  :  int
  __
  * **customer_id**  :  int
}

entity cart_positions {
  * **id**  :  int
  __
  * **product_sku**  :  varchar
  --
  * **cart_id**  :  int
  --
  * **quantity**  :  int
}

entity orders {
  * **number**  :  int
  __
  * **customer_id**  :  int
}

entity order_lines {
  * **order_number**  :  int
  __
  * **product_sku**  :  varchar
  --
  * **product_title**  :  varchar
  --
  * **price**  :  float
  --
  * **quantity**  :  int
}

order_lines }o--o| orders
orders }o--|| customers
cart_positions }o--|| products
cart_positions }o--|| carts
carts }o--|| customers

@enduml
